[package]
name = "hyper-with-routerify"
version = "0.1.0"
authors = ["Rousan Ali <rousanali786@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.14"
routerify="2.0.0-beta-4"
tokio = { version = "1", features = ["full"] }
